In [22]:
import time
before = time.time()
sum = 0

for i in range(100000000) :
    sum = sum + i

after = time.time()
t_taken = after - before
sum,t_taken

(4999999950000000, 22.477070569992065)

In [27]:
import numpy as np
import time
before = time.time()
sum = 0
number = np.arange(100000000)
sum = np.sum(number,dtype = np.uint64)
after = time.time()
ttaken = after - before
sum,ttaken

factor = t_taken / ttaken

print("sum = " ,sum,"and time taken = ", ttaken)

print("Numpy is", factor , "times faster than standard python")


sum =  4999999950000000 and time taken =  0.4717123508453369
Numpy is 47.64995135215731 times faster than standard python


In [30]:
import numpy

a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
b = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [34]:
b.shape

(2, 10)

In [35]:
n = np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
x.shape

(12,)

In [38]:
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
n1 = [1,2,3]
n2 = [4,5,6]
n3 = [7,8,9]
a = np.array([n1+n2+n3])
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
a=np.array([1,2])
b=np.array([3,4])
c= a+b
c

array([4, 6])

In [43]:
d=[1,2]
e=[3,4]
f= d+e
f

[1, 2, 3, 4]

In [44]:
np.array(f)

array([1, 2, 3, 4])

In [45]:
g = np.array([1,2,3])
3 * g

array([3, 6, 9])

In [46]:
g + [4]

array([5, 6, 7])

In [47]:
i = np.array([[1,2,3],[4,5,6]])
i

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.sum(i)

21

In [52]:
np.sum(i, axis=1)

array([ 6, 15])

In [56]:
np.sum(i,axis=0)

array([5, 7, 9])

In [57]:
np.min(i)

1

In [58]:
np.max(i)

6

In [61]:
np.average(i)

3.5

In [65]:
i[1,1]

5

In [68]:
i[0,1]

2

In [69]:
i[0,-2]

2

In [74]:
n = np.arange(1,21)
n1 = n.reshape(4,5)
n1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [79]:
n2=np.arange(21,26)
n2

array([21, 22, 23, 24, 25])

In [81]:
np.append(n1,[n2],axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
n3=np.arange(21,26)
n3=n3.reshape(1,5)
n3

array([[21, 22, 23, 24, 25]])

In [90]:
t=np.append(n1,n3,axis=0)
t

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
n4=n3.reshape(5,1)
n4

array([[21],
       [22],
       [23],
       [24],
       [25]])

In [89]:
np.append(t,n4,axis=1)

array([[ 1,  2,  3,  4,  5, 21],
       [ 6,  7,  8,  9, 10, 22],
       [11, 12, 13, 14, 15, 23],
       [16, 17, 18, 19, 20, 24],
       [21, 22, 23, 24, 25, 25]])

In [5]:
import pandas as pd

data = pd.read_csv("track.csv",encoding = "latin1")

In [6]:
data

track_id                                               name  album_id  \
0            1            For Those About To Rock (We Salute You)         1   
1            2                                  Balls to the Wall         2   
2            3                                    Fast As a Shark         3   
3            4                                  Restless and Wild         3   
4            5                               Princess of the Dawn         3   
...        ...                                                ...       ...   
3498      3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...       343   
3499      3500  String Quartet No. 12 in C Minor, D. 703 "Quar...       344   
3500      3501               L'orfeo, Act 3, Sinfonia (Orchestra)       345   
3501      3502  Quintet for Horn, Violin, 2 Violas, and Cello ...       346   
3502      3503                                      Koyaanisqatsi       347   

      media_type_id  genre_id  \
0                 1         1   
1                 2         1   
2                 2         1   
3                 2         1   
4                 2         1   
...             ...       ...   
3498              2        24   
3499              2        24   
3500              2        24   
3501              2        24   
3502              2        10   

                                               composer  milliseconds  \
0             Angus Young, Malcolm Young, Brian Johnson        343719   
1                                                   NaN        342562   
2     F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...        230619   
3     F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...        252051   
4                            Deaffy & R.A. Smith-Diesel        375418   
...                                                 ...           ...   
3498                                                NaN        286741   
3499                                     Franz Schubert        139200   
3500                                 Claudio Monteverdi         66639   
3501                            Wolfgang Amadeus Mozart        221331   
3502                                       Philip Glass        206005   

         bytes  unit_price  
0     11170334        0.99  
1      5510424        0.99  
2      3990994        0.99  
3      4331779        0.99  
4      6290521        0.99  
...        ...         ...  
3498   4718950        0.99  
3499   2283131        0.99  
3500   1189062        0.99  
3501   3665114        0.99  
3502   3305164        0.99  

[3503 rows x 9 columns]

In [8]:
data.head()

track_id                                     name  album_id  media_type_id  \
0         1  For Those About To Rock (We Salute You)         1              1   
1         2                        Balls to the Wall         2              2   
2         3                          Fast As a Shark         3              2   
3         4                        Restless and Wild         3              2   
4         5                     Princess of the Dawn         3              2   

   genre_id                                           composer  milliseconds  \
0         1          Angus Young, Malcolm Young, Brian Johnson        343719   
1         1                                                NaN        342562   
2         1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...        230619   
3         1  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...        252051   
4         1                         Deaffy & R.A. Smith-Diesel        375418   

      bytes  unit_price  
0  11170334        0.99  
1   5510424        0.99  
2   3990994        0.99  
3   4331779        0.99  
4   6290521        0.99

In [9]:
data.tail()

track_id                                               name  album_id  \
3498      3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...       343   
3499      3500  String Quartet No. 12 in C Minor, D. 703 "Quar...       344   
3500      3501               L'orfeo, Act 3, Sinfonia (Orchestra)       345   
3501      3502  Quintet for Horn, Violin, 2 Violas, and Cello ...       346   
3502      3503                                      Koyaanisqatsi       347   

      media_type_id  genre_id                 composer  milliseconds    bytes  \
3498              2        24                      NaN        286741  4718950   
3499              2        24           Franz Schubert        139200  2283131   
3500              2        24       Claudio Monteverdi         66639  1189062   
3501              2        24  Wolfgang Amadeus Mozart        221331  3665114   
3502              2        10             Philip Glass        206005  3305164   

      unit_price  
3498        0.99  
3499        0.99  
3500        0.99  
3501        0.99  
3502        0.99

In [10]:
data.tail(3)

track_id                                               name  album_id  \
3500      3501               L'orfeo, Act 3, Sinfonia (Orchestra)       345   
3501      3502  Quintet for Horn, Violin, 2 Violas, and Cello ...       346   
3502      3503                                      Koyaanisqatsi       347   

      media_type_id  genre_id                 composer  milliseconds    bytes  \
3500              2        24       Claudio Monteverdi         66639  1189062   
3501              2        24  Wolfgang Amadeus Mozart        221331  3665114   
3502              2        10             Philip Glass        206005  3305164   

      unit_price  
3500        0.99  
3501        0.99  
3502        0.99

In [11]:
data.head(3)

track_id                                     name  album_id  media_type_id  \
0         1  For Those About To Rock (We Salute You)         1              1   
1         2                        Balls to the Wall         2              2   
2         3                          Fast As a Shark         3              2   

   genre_id                                           composer  milliseconds  \
0         1          Angus Young, Malcolm Young, Brian Johnson        343719   
1         1                                                NaN        342562   
2         1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...        230619   

      bytes  unit_price  
0  11170334        0.99  
1   5510424        0.99  
2   3990994        0.99

In [18]:
import pandas as pd

df = pd.read_excel("karigar.xlsx")

In [19]:
df

ID FirstName   LastName  Salary Address
0   1      Balu      Patel    2000       A
1   2        Md     Ismail    2500       B
2   3        Md      Nazim    2200       C
3   4        Md    Mukhtar    2300       D
4   5        Md   Farooque    3000       E
5   6    Nandan      Patel    2500       F
6   7     Dakya      Patel    1800       G
7   8        Md  Mushtaque    3100       H
8   9        Md     Mohsin    2200       I
9  10     Vilas       Kaka    2500       J

In [21]:
df1 = pd.read_excel("F:\karigar.xlsx")

In [22]:
df1

ID FirstName   LastName  Salary Address
0   1      Balu      Patel    2000       A
1   2        Md     Ismail    2500       B
2   3        Md      Nazim    2200       C
3   4        Md    Mukhtar    2300       D
4   5        Md   Farooque    3000       E
5   6    Nandan      Patel    2500       F
6   7     Dakya      Patel    1800       G
7   8        Md  Mushtaque    3100       H
8   9        Md     Mohsin    2200       I
9  10     Vilas       Kaka    2500       J

In [23]:
s = pd.sum(salary)

AttributeError: module 'pandas' has no attribute 'sum'

In [47]:
from math import ceil,floor,trunc,exp,pow,sqrt,log,pi,e,radians,sin,fsum,gcd,factorial
i = 3.5
j = -3.5
k = 2
l = [1,2,3,4,5]
ceil(i),floor(i),trunc(i),ceil(j),floor(j),trunc(j),exp(2),pow(10,2),sqrt(100),log(100),log(100,10),pi,e,sin(90),sin(radians(90)),sum(l),fsum(l),gcd(20,100),factorial(5)

(4,
 3,
 3,
 -3,
 -4,
 -3,
 7.38905609893065,
 100.0,
 10.0,
 4.605170185988092,
 2.0,
 3.141592653589793,
 2.718281828459045,
 0.8939966636005579,
 1.0,
 15,
 15.0,
 20,
 120)

In [48]:
import numpy as np

In [50]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [52]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [60]:
np.random.rand(2,2,2)

array([[[0.0399479 , 0.64123563],
        [0.68806207, 0.0139646 ]],

       [[0.96274391, 0.08328607],
        [0.07709438, 0.72448839]]])

In [56]:
d = np.random.randint(0,10,size=(5,5))

In [57]:
d

array([[8, 6, 7, 4, 4],
       [3, 3, 0, 3, 0],
       [7, 5, 9, 0, 2],
       [6, 1, 9, 0, 4],
       [7, 8, 0, 1, 4]])

In [61]:
d[:,:]

array([[8, 6, 7, 4, 4],
       [3, 3, 0, 3, 0],
       [7, 5, 9, 0, 2],
       [6, 1, 9, 0, 4],
       [7, 8, 0, 1, 4]])

In [62]:
a=np.ones((3,3))

In [63]:
b=np.zeros((3,3))

In [65]:
np.concatenate([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
d=np.concatenate([a,b],axis=1)

In [89]:
c=np.vstack([a,b])

In [88]:
np.hstack([a,b])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [98]:
d1,d2=np.split(c,[2])

In [99]:
d1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [100]:
d2

array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
e1,e2=np.vsplit(c,[2])

In [102]:
e1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [103]:
e2

array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
d.ndim

2

In [106]:
d.shape

(3, 6)

In [107]:
d.size

18

In [112]:
a=np.arange(1,7)

In [113]:
a

array([1, 2, 3, 4, 5, 6])

In [114]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [115]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [155]:
a = np.array([[1,1,],[3,2]])

In [156]:
a

array([[1, 1],
       [3, 2]])

In [157]:
b = np.array([[2,3],[4,5],[7,8]])

In [158]:
b

array([[2, 3],
       [4, 5],
       [7, 8]])

In [161]:
a.reshape(2,1,2)

array([[[1, 1]],

       [[3, 2]]])

In [152]:
b.reshape(1,3,2)

array([[[2, 3],
        [4, 5],
        [7, 8]]])

In [146]:
d= a.reshape(2,1,2) + b.reshape(1,3,2)

In [147]:
d

array([[[ 3,  4],
        [ 5,  6],
        [ 8,  9]],

       [[ 5,  5],
        [ 7,  7],
        [10, 10]]])

In [148]:
d.ndim

3

In [162]:
d= a.reshape(2,1,2) - b.reshape(1,3,2)

In [164]:
d

array([[[-1, -2],
        [-3, -4],
        [-6, -7]],

       [[ 1, -1],
        [-1, -3],
        [-4, -6]]])